#!/bin/bash

words=$(for file in $(find $1 -type f); do
cat $file | tr ' ' '\n'
done | sort | uniq)

for word in $words; do
	for file in $(find $1 -type f); do
		 grep -Hw $word $file 2> /dev/null
	done
done 
